{"name": "test_homep", "status": "broken", "statusDetails": {"message": "TypeError: 'tuple' object is not callable", "trace": "self = <tests.test.test_hp.TestHome object at 0x000001AAD0E080E0>\n\n    def test_homep(self):\n        home_page = HomePage(self.driver)\n>       cameras_page = HomePage.cameras_tab()\nE       TypeError: 'tuple' object is not callable\n\ntest_hp.py:13: TypeError"}, "start": 1717997972800, "stop": 1717997972801, "uuid": "56954daa-3297-41fe-ae30-cfe62ed3776f", "historyId": "70663d29abc3984a3ba5955cb8a644f0", "testCaseId": "70663d29abc3984a3ba5955cb8a644f0", "fullName": "tests.test.test_hp.TestHome#test_homep", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests.test"}, {"name": "suite", "value": "test_hp"}, {"name": "subSuite", "value": "TestHome"}, {"name": "host", "value": "ASUS15KJ"}, {"name": "thread", "value": "2216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.test_hp"}]}